<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $modules = array(
            array('id' => '1','title' => 'Products','slug' => 'products','created_at' => NULL,'updated_at' => NULL),
            array('id' => '2','title' => 'Sales','slug' => 'sales','created_at' => NULL,'updated_at' => NULL),
            array('id' => '3','title' => 'Dashboard','slug' => 'dashboard','created_at' => NULL,'updated_at' => NULL),
            array('id' => '4','title' => 'Invoice','slug' => 'invoice','created_at' => NULL,'updated_at' => NULL),
            array('id' => '5','title' => 'Admin','slug' => 'admin','created_at' => NULL,'updated_at' => NULL),
            array('id' => '6','title' => 'Expense','slug' => 'expense','created_at' => NULL,'updated_at' => NULL),
            array('id' => '7','title' => 'General Options','slug' => 'general-options','created_at' => NULL,'updated_at' => NULL),
            array('id' => '8','title' => 'Customers','slug' => 'customer','created_at' => NULL,'updated_at' => NULL),
            array('id' => '9','title' => 'Cashes','slug' => 'cashes','created_at' => NULL,'updated_at' => NULL),
            array('id' => '10','title' => 'Price','slug' => 'price','created_at' => NULL,'updated_at' => NULL),
            array('id' => '11','title' => 'Suppliers','slug' => 'suppliers','created_at' => NULL,'updated_at' => NULL),
            array('id' => '12','title' => 'Reports','slug' => 'reports','created_at' => NULL,'updated_at' => NULL),
            array('id' => '13','title' => 'Others','slug' => 'others','created_at' => NULL,'updated_at' => NULL)
        );


        $model_has_permissions = array(
        );


        $model_has_roles = array(
            array('role_id' => '1','model_type' => 'App\\Admin','model_id' => '1'),
            array('role_id' => '1','model_type' => 'App\\Admin','model_id' => '2'),
            array('role_id' => '3','model_type' => 'App\\Admin','model_id' => '5'),
            array('role_id' => '3','model_type' => 'App\\Admin','model_id' => '6'),
            array('role_id' => '6','model_type' => 'App\\Admin','model_id' => '7'),
            array('role_id' => '6','model_type' => 'App\\Admin','model_id' => '8'),
            array('role_id' => '6','model_type' => 'App\\Admin','model_id' => '9'),
            array('role_id' => '6','model_type' => 'App\\Admin','model_id' => '10')
        );


        $permissions = [
            ['module_id' => '3', 'name' => 'dashboard.delivery', 'display_name' => 'Dashboard Delivery View', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '3', 'name' => 'dashboard.sales', 'display_name' => 'Dashboard Sales Information', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '3', 'name' => 'dashboard.cash', 'display_name' => 'Dashboard Cash Information', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '3', 'name' => 'dashboard.return', 'display_name' => 'Dashboard Return Information', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '3', 'name' => 'business.chart', 'display_name' => 'Business Chart', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '3', 'name' => 'dashboard.overview', 'display_name' => 'Dashboard Overview Counter', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '3', 'name' => 'dashboard.chart', 'display_name' => 'Dashboard Chart', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '13', 'name' => 'sms.logs', 'display_name' => 'SMS Logs', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '1', 'name' => 'stock.display', 'display_name' => 'Stock Display', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '1', 'name' => 'stock.edit', 'display_name' => 'Stock Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            ['module_id' => '4', 'name' => 'challan.index', 'display_name' => 'Challan List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'challan.create', 'display_name' => 'Challan Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'challan.show', 'display_name' => 'Challan Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'challan.edit', 'display_name' => 'Challan Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'challan.delete', 'display_name' => 'Challan Delete', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense.index', 'display_name' => 'Expense List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense.create', 'display_name' => 'Expense Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense.edit', 'display_name' => 'Expense Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense.show', 'display_name' => 'Expense Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense.delete', 'display_name' => 'Expense Delete', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense_type.index', 'display_name' => 'Expense Type List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense_type.create', 'display_name' => 'Expense Type Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense_type.edit', 'display_name' => 'Expense Type Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense_type.show', 'display_name' => 'Expense Type Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '6', 'name' => 'expense_type.delete', 'display_name' => 'Expense Type Delete', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '7', 'name' => 'general_options.show', 'display_name' => 'General Options', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '7', 'name' => 'general_options.update', 'display_name' => 'General Options Edit/Update', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'mpo_customers.index', 'display_name' => 'MPO Customer List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'mpo_customers.edit', 'display_name' => 'MPO Customer Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'mpo_customers.create', 'display_name' => 'MPO Customer Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'mpo_customers.show', 'display_name' => 'MPO Customer Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'mpo_customers.delete', 'display_name' => 'MPO Customer Delete', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'previous_due.index', 'display_name' => 'Previous Due List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'previous_due.create', 'display_name' => 'Previous Due Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'previous_due.edit', 'display_name' => 'Previous Due Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'previous_due.delete', 'display_name' => 'Previous Due Delete', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'sales_invoice.index', 'display_name' => 'Sales Invoice List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'sales_invoice.create', 'display_name' => 'Sales Invoice Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'sales_invoice.edit', 'display_name' => 'Sales Invoice Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'sales_invoice.show', 'display_name' => 'Sales Invoice Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'sales_invoice.cancel', 'display_name' => 'Sales Invoice Cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'sales_invoice.approve', 'display_name' => 'Sales Invoice Approve', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '9', 'name' => 'cash.index', 'display_name' => 'Cash List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '9', 'name' => 'cash.create', 'display_name' => 'Cash Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '9', 'name' => 'cash.edit', 'display_name' => 'Cash Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '9', 'name' => 'cash.cancel', 'display_name' => 'Cash Cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '9', 'name' => 'cash.approve', 'display_name' => 'Cash Approve', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'return_invoice.index', 'display_name' => 'Return Invoice List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'return_invoice.edit', 'display_name' => 'Return Invoice Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'return_invoice.create', 'display_name' => 'Return Invoice Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'return_invoice.cancel', 'display_name' => 'Return Invoice Cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'return_invoice.approve', 'display_name' => 'Return Invoice Approve', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '13', 'name' => 'company_info.index', 'display_name' => 'Company Information Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '13', 'name' => 'company_info.edit', 'display_name' => 'Company Information Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '10', 'name' => 'trade_price.index', 'display_name' => 'Trade Price List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '10', 'name' => 'trade_price.edit', 'display_name' => 'Trade Price Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'purchase.index', 'display_name' => 'Purchase List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'purchase.show', 'display_name' => 'Purchase Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'purchase.create', 'display_name' => 'Purchase Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'purchase.edit', 'display_name' => 'Purchase Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'purchase.cancel', 'display_name' => 'Purchase cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'suppliers.index', 'display_name' => 'Suppliers List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'suppliers.edit', 'display_name' => 'Suppliers Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'suppliers.payment.index', 'display_name' => 'Suppliers Payment List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'suppliers.payment.edit', 'display_name' => 'Suppliers Payment Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'suppliers.payment.create', 'display_name' => 'Suppliers Payment Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'suppliers.payment.cancel', 'display_name' => 'Suppliers Payment Cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'supplier_due.index', 'display_name' => 'Suppliers Due List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'supplier_due.create', 'display_name' => 'Suppliers Due Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'supplier_due.edit', 'display_name' => 'Suppliers Due Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '11', 'name' => 'supplier_due.cancel', 'display_name' => 'Suppliers Due Cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '13', 'name' => 'backup', 'display_name' => 'Backup', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'customer.statements', 'display_name' => 'Customer Statements', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'customer.details.statements', 'display_name' => 'Customer Details Statements', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'customer.due.report', 'display_name' => 'Customer Due Reports', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'stock.report', 'display_name' => 'Stock Reports', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'cash.report', 'display_name' => 'Cash Reports', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'sales.report', 'display_name' => 'Sales Reports', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'delivery.report', 'display_name' => 'Delivery Reports', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'supplier_due.report', 'display_name' => 'Supplier Due Reports', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'date_wise_product.report', 'display_name' => 'Date wise Product Report', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'expense.report', 'display_name' => 'Expense', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '5', 'name' => 'admin.permission', 'display_name' => 'Admin Permission', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '5', 'name' => 'roles.permissions', 'display_name' => 'Roles and Permission', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'products.index', 'display_name' => 'Products List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'products.create', 'display_name' => 'Products Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'products.show', 'display_name' => 'Products Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'products.edit', 'display_name' => 'Products Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'products.delete', 'display_name' => 'Products Remove', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'products.index', 'display_name' => 'Products List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_size.index', 'display_name' => 'Product Size List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_size.create', 'display_name' => 'Product Size Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_size.edit', 'display_name' => 'Product Size Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_size.delete', 'display_name' => 'Product Size Remove', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_type.index', 'display_name' => 'Product Type List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_type.create', 'display_name' => 'Product Type Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_type.edit', 'display_name' => 'Product Type Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'product_type.delete', 'display_name' => 'Product Type Remove', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '13','name' => 'payment_methods', 'display_name' => 'Payment Methods', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '12', 'name' => 'sales_details.report', 'display_name' => 'Sales Details Report', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'pharmacy_customers.index', 'display_name' => 'Pharmacy Customer List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'pharmacy_customers.edit', 'display_name' => 'Pharmacy Customer Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'pharmacy_customers.create', 'display_name' => 'Pharmacy Customer Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'pharmacy_customers.show', 'display_name' => 'Pharmacy Customer Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '8', 'name' => 'pharmacy_customers.delete', 'display_name' => 'Pharmacy Customer Delete', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],

            [ 'module_id' => '4', 'name' => 'daily_order.index', 'display_name' => 'Daily Order List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'daily_order.create', 'display_name' => 'Daily Order Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'daily_order.edit', 'display_name' => 'Daily Order Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'daily_order.show', 'display_name' => 'Daily Order Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'daily_order.cancel', 'display_name' => 'Daily Order Cancel', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '4', 'name' => 'daily_order.approve', 'display_name' => 'Daily Order Approve', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],

            [ 'module_id' => '1', 'name' => 'warehouse.index', 'display_name' => 'Warehouse List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'warehouse.create', 'display_name' => 'Warehouse Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'warehouse.edit', 'display_name' => 'Warehouse Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'warehouse.show', 'display_name' => 'Warehouse Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],

            [ 'module_id' => '1', 'name' => 'brands.index', 'display_name' => 'Brands List', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'brands.create', 'display_name' => 'Brands Create', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'brands.edit', 'display_name' => 'Brands Edit', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],
            [ 'module_id' => '1', 'name' => 'brands.show', 'display_name' => 'Brands Show', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],

            [ 'module_id' => '1', 'name' => 'stock.adjustment', 'display_name' => 'Stock Adjustment', 'guard_name' => 'admin', 'created_at' => NULL, 'updated_at' => NULL],

        ];


        $roles = array(
            array('id' => '1','name' => 'Super Admin','guard_name' => 'admin','created_at' => '2020-11-08 22:48:31','updated_at' => '2020-11-08 22:48:31'),
            array('id' => '2','name' => 'Admin','guard_name' => 'admin','created_at' => '2020-11-08 22:49:49','updated_at' => '2020-11-08 23:05:33'),
            array('id' => '3','name' => 'Account Manager','guard_name' => 'admin','created_at' => '2020-11-10 16:41:11','updated_at' => '2020-11-10 16:41:11'),
            array('id' => '4','name' => 'Delivery Manger','guard_name' => 'admin','created_at' => '2020-11-11 01:52:56','updated_at' => '2020-11-11 01:52:56'),
            array('id' => '6','name' => 'Marketing Manager','guard_name' => 'admin','created_at' => '2021-01-28 16:55:12','updated_at' => '2021-01-28 16:55:12')
        );

        $role_has_permissions = array(
            array('permission_id' => '1','role_id' => '1'),
            array('permission_id' => '2','role_id' => '1'),
            array('permission_id' => '3','role_id' => '1'),
            array('permission_id' => '4','role_id' => '1'),
            array('permission_id' => '5','role_id' => '1'),
            array('permission_id' => '6','role_id' => '1'),
            array('permission_id' => '7','role_id' => '1'),
            array('permission_id' => '8','role_id' => '1'),
            array('permission_id' => '9','role_id' => '1'),
            array('permission_id' => '10','role_id' => '1'),
            array('permission_id' => '11','role_id' => '1'),
            array('permission_id' => '12','role_id' => '1'),
            array('permission_id' => '13','role_id' => '1'),
            array('permission_id' => '14','role_id' => '1'),
            array('permission_id' => '15','role_id' => '1'),
            array('permission_id' => '16','role_id' => '1'),
            array('permission_id' => '17','role_id' => '1'),
            array('permission_id' => '18','role_id' => '1'),
            array('permission_id' => '19','role_id' => '1'),
            array('permission_id' => '20','role_id' => '1'),
            array('permission_id' => '21','role_id' => '1'),
            array('permission_id' => '22','role_id' => '1'),
            array('permission_id' => '23','role_id' => '1'),
            array('permission_id' => '24','role_id' => '1'),
            array('permission_id' => '25','role_id' => '1'),
            array('permission_id' => '26','role_id' => '1'),
            array('permission_id' => '27','role_id' => '1'),
            array('permission_id' => '28','role_id' => '1'),
            array('permission_id' => '29','role_id' => '1'),
            array('permission_id' => '30','role_id' => '1'),
            array('permission_id' => '31','role_id' => '1'),
            array('permission_id' => '32','role_id' => '1'),
            array('permission_id' => '33','role_id' => '1'),
            array('permission_id' => '34','role_id' => '1'),
            array('permission_id' => '35','role_id' => '1'),
            array('permission_id' => '36','role_id' => '1'),
            array('permission_id' => '37','role_id' => '1'),
            array('permission_id' => '38','role_id' => '1'),
            array('permission_id' => '39','role_id' => '1'),
            array('permission_id' => '40','role_id' => '1'),
            array('permission_id' => '41','role_id' => '1'),
            array('permission_id' => '42','role_id' => '1'),
            array('permission_id' => '43','role_id' => '1'),
            array('permission_id' => '44','role_id' => '1'),
            array('permission_id' => '45','role_id' => '1'),
            array('permission_id' => '46','role_id' => '1'),
            array('permission_id' => '47','role_id' => '1'),
            array('permission_id' => '48','role_id' => '1'),
            array('permission_id' => '49','role_id' => '1'),
            array('permission_id' => '50','role_id' => '1'),
            array('permission_id' => '51','role_id' => '1'),
            array('permission_id' => '52','role_id' => '1'),
            array('permission_id' => '53','role_id' => '1'),
            array('permission_id' => '54','role_id' => '1'),
            array('permission_id' => '55','role_id' => '1'),
            array('permission_id' => '56','role_id' => '1'),
            array('permission_id' => '57','role_id' => '1'),
            array('permission_id' => '58','role_id' => '1'),
            array('permission_id' => '59','role_id' => '1'),
            array('permission_id' => '60','role_id' => '1'),
            array('permission_id' => '61','role_id' => '1'),
            array('permission_id' => '62','role_id' => '1'),
            array('permission_id' => '63','role_id' => '1'),
            array('permission_id' => '64','role_id' => '1'),
            array('permission_id' => '65','role_id' => '1'),
            array('permission_id' => '66','role_id' => '1'),
            array('permission_id' => '67','role_id' => '1'),
            array('permission_id' => '68','role_id' => '1'),
            array('permission_id' => '69','role_id' => '1'),
            array('permission_id' => '70','role_id' => '1'),
            array('permission_id' => '71','role_id' => '1'),
            array('permission_id' => '72','role_id' => '1'),
            array('permission_id' => '73','role_id' => '1'),
            array('permission_id' => '74','role_id' => '1'),
            array('permission_id' => '75','role_id' => '1'),
            array('permission_id' => '76','role_id' => '1'),
            array('permission_id' => '77','role_id' => '1'),
            array('permission_id' => '78','role_id' => '1'),
            array('permission_id' => '79','role_id' => '1'),
            array('permission_id' => '80','role_id' => '1'),
            array('permission_id' => '81','role_id' => '1'),
            array('permission_id' => '82','role_id' => '1'),
            array('permission_id' => '83','role_id' => '1'),
            array('permission_id' => '84','role_id' => '1'),
            array('permission_id' => '85','role_id' => '1'),
            array('permission_id' => '86','role_id' => '1'),
            array('permission_id' => '87','role_id' => '1'),
            array('permission_id' => '88','role_id' => '1'),
            array('permission_id' => '89','role_id' => '1'),
            array('permission_id' => '90','role_id' => '1'),
            array('permission_id' => '91','role_id' => '1'),
            array('permission_id' => '92','role_id' => '1'),
            array('permission_id' => '93','role_id' => '1'),
            array('permission_id' => '94','role_id' => '1'),
            array('permission_id' => '95','role_id' => '1'),
            array('permission_id' => '96','role_id' => '1'),
            array('permission_id' => '97','role_id' => '1'),
            array('permission_id' => '98','role_id' => '1'),
            array('permission_id' => '99','role_id' => '1'),
            array('permission_id' => '100','role_id' => '1'),
            array('permission_id' => '101','role_id' => '1'),
            array('permission_id' => '102','role_id' => '1'),
            array('permission_id' => '103','role_id' => '1'),
            array('permission_id' => '104','role_id' => '1'),
            array('permission_id' => '105','role_id' => '1'),
            array('permission_id' => '106','role_id' => '1'),
            array('permission_id' => '107','role_id' => '1'),
            array('permission_id' => '108','role_id' => '1'),
            array('permission_id' => '109','role_id' => '1'),
            array('permission_id' => '110','role_id' => '1'),
            array('permission_id' => '111','role_id' => '1'),
            array('permission_id' => '112','role_id' => '1'),
            array('permission_id' => '113','role_id' => '1'),
            array('permission_id' => '114','role_id' => '1'),
            array('permission_id' => '115','role_id' => '1'),
            array('permission_id' => '116','role_id' => '1'),
            array('permission_id' => '117','role_id' => '1'),
            array('permission_id' => '118','role_id' => '1'),
            array('permission_id' => '119','role_id' => '1'),
            array('permission_id' => '120','role_id' => '1'),
            array('permission_id' => '1','role_id' => '2'),
            array('permission_id' => '2','role_id' => '2'),
            array('permission_id' => '3','role_id' => '2'),
            array('permission_id' => '4','role_id' => '2'),
            array('permission_id' => '5','role_id' => '2'),
            array('permission_id' => '6','role_id' => '2'),
            array('permission_id' => '7','role_id' => '2'),
            array('permission_id' => '8','role_id' => '2'),
            array('permission_id' => '9','role_id' => '2'),
            array('permission_id' => '10','role_id' => '2'),
            array('permission_id' => '11','role_id' => '2'),
            array('permission_id' => '12','role_id' => '2'),
            array('permission_id' => '13','role_id' => '2'),
            array('permission_id' => '14','role_id' => '2'),
            array('permission_id' => '15','role_id' => '2'),
            array('permission_id' => '16','role_id' => '2'),
            array('permission_id' => '17','role_id' => '2'),
            array('permission_id' => '18','role_id' => '2'),
            array('permission_id' => '19','role_id' => '2'),
            array('permission_id' => '20','role_id' => '2'),
            array('permission_id' => '21','role_id' => '2'),
            array('permission_id' => '22','role_id' => '2'),
            array('permission_id' => '23','role_id' => '2'),
            array('permission_id' => '24','role_id' => '2'),
            array('permission_id' => '25','role_id' => '2'),
            array('permission_id' => '26','role_id' => '2'),
            array('permission_id' => '27','role_id' => '2'),
            array('permission_id' => '28','role_id' => '2'),
            array('permission_id' => '29','role_id' => '2'),
            array('permission_id' => '30','role_id' => '2'),
            array('permission_id' => '31','role_id' => '2'),
            array('permission_id' => '32','role_id' => '2'),
            array('permission_id' => '33','role_id' => '2'),
            array('permission_id' => '34','role_id' => '2'),
            array('permission_id' => '35','role_id' => '2'),
            array('permission_id' => '36','role_id' => '2'),
            array('permission_id' => '37','role_id' => '2'),
            array('permission_id' => '38','role_id' => '2'),
            array('permission_id' => '39','role_id' => '2'),
            array('permission_id' => '40','role_id' => '2'),
            array('permission_id' => '43','role_id' => '2'),
            array('permission_id' => '44','role_id' => '2'),
            array('permission_id' => '45','role_id' => '2'),
            array('permission_id' => '48','role_id' => '2'),
            array('permission_id' => '49','role_id' => '2'),
            array('permission_id' => '50','role_id' => '2'),
            array('permission_id' => '53','role_id' => '2'),
            array('permission_id' => '54','role_id' => '2'),
            array('permission_id' => '55','role_id' => '2'),
            array('permission_id' => '56','role_id' => '2'),
            array('permission_id' => '57','role_id' => '2'),
            array('permission_id' => '58','role_id' => '2'),
            array('permission_id' => '59','role_id' => '2'),
            array('permission_id' => '60','role_id' => '2'),
            array('permission_id' => '62','role_id' => '2'),
            array('permission_id' => '63','role_id' => '2'),
            array('permission_id' => '64','role_id' => '2'),
            array('permission_id' => '65','role_id' => '2'),
            array('permission_id' => '66','role_id' => '2'),
            array('permission_id' => '68','role_id' => '2'),
            array('permission_id' => '69','role_id' => '2'),
            array('permission_id' => '70','role_id' => '2'),
            array('permission_id' => '72','role_id' => '2'),
            array('permission_id' => '73','role_id' => '2'),
            array('permission_id' => '74','role_id' => '2'),
            array('permission_id' => '75','role_id' => '2'),
            array('permission_id' => '76','role_id' => '2'),
            array('permission_id' => '77','role_id' => '2'),
            array('permission_id' => '78','role_id' => '2'),
            array('permission_id' => '79','role_id' => '2'),
            array('permission_id' => '80','role_id' => '2'),
            array('permission_id' => '81','role_id' => '2'),
            array('permission_id' => '82','role_id' => '2'),
            array('permission_id' => '85','role_id' => '2'),
            array('permission_id' => '86','role_id' => '2'),
            array('permission_id' => '87','role_id' => '2'),
            array('permission_id' => '88','role_id' => '2'),
            array('permission_id' => '89','role_id' => '2'),
            array('permission_id' => '90','role_id' => '2'),
            array('permission_id' => '91','role_id' => '2'),
            array('permission_id' => '92','role_id' => '2'),
            array('permission_id' => '93','role_id' => '2'),
            array('permission_id' => '94','role_id' => '2'),
            array('permission_id' => '95','role_id' => '2'),
            array('permission_id' => '96','role_id' => '2'),
            array('permission_id' => '97','role_id' => '2'),
            array('permission_id' => '98','role_id' => '2'),
            array('permission_id' => '99','role_id' => '2'),
            array('permission_id' => '100','role_id' => '2'),
            array('permission_id' => '101','role_id' => '2'),
            array('permission_id' => '102','role_id' => '2'),
            array('permission_id' => '103','role_id' => '2'),
            array('permission_id' => '104','role_id' => '2'),
            array('permission_id' => '105','role_id' => '2'),
            array('permission_id' => '106','role_id' => '2'),
            array('permission_id' => '107','role_id' => '2'),
            array('permission_id' => '108','role_id' => '2'),
            array('permission_id' => '109','role_id' => '2'),
            array('permission_id' => '110','role_id' => '2'),
            array('permission_id' => '112','role_id' => '2'),
            array('permission_id' => '113','role_id' => '2'),
            array('permission_id' => '114','role_id' => '2'),
            array('permission_id' => '115','role_id' => '2'),
            array('permission_id' => '116','role_id' => '2'),
            array('permission_id' => '117','role_id' => '2'),
            array('permission_id' => '118','role_id' => '2'),
            array('permission_id' => '119','role_id' => '2'),
            array('permission_id' => '120','role_id' => '2'),
            array('permission_id' => '1','role_id' => '3'),
            array('permission_id' => '2','role_id' => '3'),
            array('permission_id' => '3','role_id' => '3'),
            array('permission_id' => '4','role_id' => '3'),
            array('permission_id' => '5','role_id' => '3'),
            array('permission_id' => '6','role_id' => '3'),
            array('permission_id' => '7','role_id' => '3'),
            array('permission_id' => '8','role_id' => '3'),
            array('permission_id' => '9','role_id' => '3'),
            array('permission_id' => '11','role_id' => '3'),
            array('permission_id' => '12','role_id' => '3'),
            array('permission_id' => '13','role_id' => '3'),
            array('permission_id' => '14','role_id' => '3'),
            array('permission_id' => '15','role_id' => '3'),
            array('permission_id' => '16','role_id' => '3'),
            array('permission_id' => '17','role_id' => '3'),
            array('permission_id' => '18','role_id' => '3'),
            array('permission_id' => '19','role_id' => '3'),
            array('permission_id' => '20','role_id' => '3'),
            array('permission_id' => '21','role_id' => '3'),
            array('permission_id' => '22','role_id' => '3'),
            array('permission_id' => '23','role_id' => '3'),
            array('permission_id' => '24','role_id' => '3'),
            array('permission_id' => '25','role_id' => '3'),
            array('permission_id' => '26','role_id' => '3'),
            array('permission_id' => '27','role_id' => '3'),
            array('permission_id' => '28','role_id' => '3'),
            array('permission_id' => '29','role_id' => '3'),
            array('permission_id' => '30','role_id' => '3'),
            array('permission_id' => '31','role_id' => '3'),
            array('permission_id' => '32','role_id' => '3'),
            array('permission_id' => '33','role_id' => '3'),
            array('permission_id' => '34','role_id' => '3'),
            array('permission_id' => '35','role_id' => '3'),
            array('permission_id' => '36','role_id' => '3'),
            array('permission_id' => '37','role_id' => '3'),
            array('permission_id' => '38','role_id' => '3'),
            array('permission_id' => '39','role_id' => '3'),
            array('permission_id' => '40','role_id' => '3'),
            array('permission_id' => '43','role_id' => '3'),
            array('permission_id' => '44','role_id' => '3'),
            array('permission_id' => '45','role_id' => '3'),
            array('permission_id' => '48','role_id' => '3'),
            array('permission_id' => '49','role_id' => '3'),
            array('permission_id' => '50','role_id' => '3'),
            array('permission_id' => '53','role_id' => '3'),
            array('permission_id' => '54','role_id' => '3'),
            array('permission_id' => '55','role_id' => '3'),
            array('permission_id' => '56','role_id' => '3'),
            array('permission_id' => '57','role_id' => '3'),
            array('permission_id' => '58','role_id' => '3'),
            array('permission_id' => '59','role_id' => '3'),
            array('permission_id' => '60','role_id' => '3'),
            array('permission_id' => '62','role_id' => '3'),
            array('permission_id' => '63','role_id' => '3'),
            array('permission_id' => '64','role_id' => '3'),
            array('permission_id' => '65','role_id' => '3'),
            array('permission_id' => '66','role_id' => '3'),
            array('permission_id' => '68','role_id' => '3'),
            array('permission_id' => '69','role_id' => '3'),
            array('permission_id' => '70','role_id' => '3'),
            array('permission_id' => '72','role_id' => '3'),
            array('permission_id' => '73','role_id' => '3'),
            array('permission_id' => '74','role_id' => '3'),
            array('permission_id' => '75','role_id' => '3'),
            array('permission_id' => '77','role_id' => '3'),
            array('permission_id' => '78','role_id' => '3'),
            array('permission_id' => '79','role_id' => '3'),
            array('permission_id' => '80','role_id' => '3'),
            array('permission_id' => '81','role_id' => '3'),
            array('permission_id' => '82','role_id' => '3'),
            array('permission_id' => '85','role_id' => '3'),
            array('permission_id' => '86','role_id' => '3'),
            array('permission_id' => '87','role_id' => '3'),
            array('permission_id' => '88','role_id' => '3'),
            array('permission_id' => '89','role_id' => '3'),
            array('permission_id' => '90','role_id' => '3'),
            array('permission_id' => '91','role_id' => '3'),
            array('permission_id' => '92','role_id' => '3'),
            array('permission_id' => '93','role_id' => '3'),
            array('permission_id' => '94','role_id' => '3'),
            array('permission_id' => '95','role_id' => '3'),
            array('permission_id' => '96','role_id' => '3'),
            array('permission_id' => '97','role_id' => '3'),
            array('permission_id' => '98','role_id' => '3'),
            array('permission_id' => '99','role_id' => '3'),
            array('permission_id' => '100','role_id' => '3'),
            array('permission_id' => '101','role_id' => '3'),
            array('permission_id' => '102','role_id' => '3'),
            array('permission_id' => '103','role_id' => '3'),
            array('permission_id' => '104','role_id' => '3'),
            array('permission_id' => '105','role_id' => '3'),
            array('permission_id' => '106','role_id' => '3'),
            array('permission_id' => '107','role_id' => '3'),
            array('permission_id' => '108','role_id' => '3'),
            array('permission_id' => '109','role_id' => '3'),
            array('permission_id' => '110','role_id' => '3'),
            array('permission_id' => '111','role_id' => '3'),
            array('permission_id' => '112','role_id' => '3'),
            array('permission_id' => '113','role_id' => '3'),
            array('permission_id' => '114','role_id' => '3'),
            array('permission_id' => '115','role_id' => '3'),
            array('permission_id' => '116','role_id' => '3'),
            array('permission_id' => '117','role_id' => '3'),
            array('permission_id' => '118','role_id' => '3'),
            array('permission_id' => '119','role_id' => '3')
        );

        DB::table('roles')->delete();
        DB::table('permissions')->delete();
        DB::table('modules')->delete();
        DB::table('model_has_roles')->delete();
        DB::table('role_has_permissions')->delete();
        DB::table('model_has_permissions')->delete();

        $max_roles = DB::table('roles')->max('id') + 1;
        DB::statement("ALTER TABLE roles AUTO_INCREMENT =  $max_roles");

        $max_permissions= DB::table('permissions')->max('id') + 1;
        DB::statement("ALTER TABLE permissions AUTO_INCREMENT =  $max_permissions");

        $max_modules = DB::table('modules')->max('id') + 1;
        DB::statement("ALTER TABLE modules AUTO_INCREMENT =  $max_modules");

        DB::table('modules')->insert($modules);
        DB::table('roles')->insert($roles);
        DB::table('permissions')->insert($permissions);
        DB::table('model_has_roles')->insert($model_has_roles);
        DB::table('role_has_permissions')->insert($role_has_permissions);
        DB::table('model_has_permissions')->insert($model_has_permissions);
    }
}
